name: notebook
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.3.3
  - async_generator=1.10
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - blinker=1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - certipy=0.1.3
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - idna=2.8
  - importlib_metadata=1.5.0
  - inflect=4.0.0
  - ipykernel=5.1.4
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jinja2=2.11.0
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter_telemetry=0.0.4
  - jupyterhub-base=1.1.0
  - jupyterhub-singleuser=1.1.0
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libcurl=7.65.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgomp=9.2.0
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - mako=1.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=6.0.3
  - nteract_on_jupyter=2.1.3
  - oauthlib=3.0.1
  - openssl=1.1.1f
  - pamela=1.0.0
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - parso=0.6.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pycurl=7.43.0.5
  - pygments=2.5.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-json-logger=0.1.11
  - pyzmq=18.1.1
  - readline=8.0
  - requests=2.22.0
  - ruamel.yaml=0.16.6
  - ruamel.yaml.clib=0.2.0
  - send2trash=1.5.0
  - setuptools=45.1.0
  - six=1.14.0
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.1
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=2.1.0
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - click==7.1.1
    - cycler==0.10.0
    - ipython==7.9.0
    - jovian==0.2.14
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - jupyter-offlinenotebook==0.0.11
    - kiwisolver==1.1.0
    - matplotlib==3.2.1
    - numpy==1.18.2
    - pandas==0.25.3
    - prompt-toolkit==2.0.10
    - pyparsing==2.4.7
    - pytz==2019.3
    - pyyaml==5.3.1
    - qtconsole==4.7.2
    - qtpy==1.9.0
    - scipy==1.4.1
    - seaborn==0.10.1
    - uuid==1.30
prefix: /srv/conda/envs/notebook

